# Generated by Django 5.2.7 on 2025-10-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sinis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='Cliente')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='Cliente')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='Cliente')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='Cliente')),
                ('imagen5', models.ImageField(blank=True, null=True, upload_to='Cliente')),
                ('expli1', models.CharField(blank=True, max_length=100)),
                ('expli2', models.CharField(blank=True, max_length=100)),
                ('expli3', models.CharField(blank=True, max_length=100)),
                ('expli4', models.CharField(blank=True, max_length=100)),
                ('expli5', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
