# Generated by Django 5.2.7 on 2025-10-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClienteSiniestro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sinis',
            old_name='tipo',
            new_name='asunto',
        ),
        migrations.AlterField(
            model_name='sinis',
            name='fecha',
            field=models.DateField(),
        ),
    ]
