# Generated by Django 5.2.7 on 2025-10-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClienteSiniestro', '0002_rename_tipo_sinis_asunto_alter_sinis_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinis',
            name='estado',
            field=models.CharField(default='pendiente', max_length=50),
        ),
    ]
